const test=require('node:test'),assert=require('node:assert/strict');
const D=require('../property-research-data.js');
const brief=require('../data/property-search-brief.json');
const valid=()=>({schemaVersion:2,generatedAt:'2026-09-21T12:00:00Z',brief,properties:[{ID:'x',Acres:'20'}],health:{status:'limited'}});
test('valid atomic snapshot accepted',()=>assert.equal(D.validate(valid()).properties.length,1));
test('legacy 50 acre snapshot rejected',()=>assert.throws(()=>D.validate({...valid(),brief:{...brief,minimumAcres:50}})));
test('old drive mandate rejected',()=>assert.throws(()=>D.validate({...valid(),brief:{...brief,maximumDriveMinutes:55}})));
test('unsupported schema rejected',()=>assert.throws(()=>D.validate({...valid(),schemaVersion:1})));
test('non-row properties rejected',()=>assert.throws(()=>D.validate({...valid(),properties:[null]})));
test('nested untyped property fields rejected',()=>assert.throws(()=>D.validate({...valid(),properties:[{Acres:20}]})));
test('missing health metadata rejected',()=>assert.throws(()=>D.validate({...valid(),health:null})));
test('unknown review stays unknown',()=>assert.equal(D.freshness({}).state,'unknown'));
test('May review is stale in September',()=>assert.equal(D.freshness({'Listing Verified At':'2026-05-11T22:30:00Z'},30,Date.parse('2026-09-21')).state,'stale'));
test('new snapshot never changes old review date',()=>assert.equal(D.freshness({'generatedAt':'2026-09-21','Last Researched':'2026-05-13'},30,Date.parse('2026-09-21')).date,'2026-05-13'));
test('actual public-page check takes precedence over legacy review',()=>assert.equal(D.freshness({'Listing Checked At':'2026-09-20','Listing Verified At':'2026-05-11'},30,Date.parse('2026-09-21')).state,'recent'));
test('future review cannot look fresh',()=>assert.equal(D.freshness({'Listing Checked At':'2027-01-01'},30,Date.parse('2026-09-21')).state,'unknown'));
test('workflow success is not portrayed as successful source coverage',()=>assert.match(D.workflowLabel({status:'completed',conclusion:'success'}),/coverage/));
test('failed workflow preserves saved research',()=>assert.match(D.workflowLabel({status:'completed',conclusion:'failure'}),/retained/));
test('partial source coverage is never a complete success',()=>assert.match(D.healthLabel({status:'partial'}),/failed/));
test('limited provider coverage is explicitly limited',()=>assert.match(D.healthLabel({status:'limited'}),/Limited/));
test('latest run ignores non-main branches',()=>assert.equal(D.latestRun([{id:10,head_branch:'feature'},{id:3,head_branch:'main'}]).id,3));
test('dispatch watcher ignores old baseline run',()=>assert.equal(D.dispatchedRun([{id:1,head_branch:'main',event:'workflow_dispatch',created_at:'2026-09-21T12:00:00Z'}],Date.parse('2026-09-21T12:00:00Z'),[1]),null));
test('dispatch watcher ignores scheduled work',()=>assert.equal(D.dispatchedRun([{id:2,head_branch:'main',event:'schedule',created_at:'2026-09-21T12:00:00Z'}],Date.parse('2026-09-21T12:00:00Z'),[]),null));
test('new dispatch identified without using an old successful run',()=>assert.equal(D.dispatchedRun([{id:2,head_branch:'main',event:'workflow_dispatch',created_at:'2026-09-21T12:00:01Z'}],Date.parse('2026-09-21T12:00:00Z'),[1]).id,2));
